languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 1

title = "ZawZaw.blog"
copyright = "&copy; 2026 ZawZaw.blog"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["blog"]
  description = "Wrties about Container technologies & networking, Kubernetes, and personal experiences."

[params.author]
  name = "Zaw Zaw"
  image = "img/author-profile.jpeg"
  headline = ""
  bio = "An SRE/platform engineerâ€”loves writing and photography."
  links = [
    { email = "mailto:zawzthein@outlook.com" },
    { rss = "/newsletter" },
    { github = "https://github.com/thezawzaw" },
    { linkedin = "https://www.linkedin.com/in/thezawzaw" },
    { medium = "https://thezawzaw.medium.com" },
    { facebook = "https://www.facebook.com/thezawzaww" },
    { instagram = "https://www.instagram.com/thezawzaw" }
  ]

