# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.
[[main]]
  name = "BLOG"
  pageRef = "blog"
  weight = 10

[[main]]
  name = "TOPICS"
  pageref = "tags"
  weight = 20

[[main]]
  name = "PHOTOGRAPHY"
  pageref = "photography"
  weight = 30

[[main]]
  name = "ABOUT"
  pageref = "about"
  weight = 40

[[main]]
  name = "Newsletter"
  pageref = "newsletter"
  weight = 50
  [main.params]
    icon = "email"
    showname = true

[[main]]
  name = "Linkedin"
  url = "https://www.linkedin.com/newsletters/the-container-stack-7401648894910349313"
  weight = 60
  [main.params]
    icon = "linkedin"
    showName = false
    target = "_blank"

[[main]]
  name = "GitHub"
  url = "https://github.com/thezawzaw"
  weight = 70
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
  name = "Blog"
  pageRef = "blog"
  weight = 10

[[footer]]
  name = "Topics"
  pageref = "tags"
  weight = 20

[[footer]]
  name = "Photography"
  pageref = "photography"
  weight = 30

[[footer]]
  name = "About"
  pageref = "about"
  weight = 40

[[footer]]
  name = "Newsletter"
  pageref = "newsletter"
  weight = 50

[[footer]]
  name = "Linkedin"
  url = "https://www.linkedin.com/newsletters/the-container-stack-7401648894910349313"
  weight = 60

