# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true
enableQuicklink = true

# robots = ""
fingerprintAlgorithm = "sha256"

[header]
  layout = "hamburger" # valid options: basic, hamburger, hybrid, custom
  # logo = "img/logo.jpg"
  # logoDark = "img/logo-dark.jpg"
  showTitle = true

[footer]
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true
  recentLimit = 6

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = true
  editURL = "https://github.com/thezawzaw/thezawzaw.github.io/tree/main/content/"
  editAppendPath = true
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = true
  showComments = false
  # sharingLinks = ["facebook", "x-twitter", "threads", "linkedin"]

[list]
  showBreadcrumbs = true
  showSummary = true
  showTableOfContents = true
  showTaxonomies = false
  groupByYear = true
  paginationWidth = 1

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true

[fathomAnalytics]
  # site = "ABC12345"

#[umamiAnalytics]
#  site = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
#  region = "eu"  # Can be either "eu" or "us"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
